module filebox{

	interface user{
	readonly attribute long uid;
	attribute string username;
	attribute string password;
	attribute long lastlogin;
	attribute short filestatus; // 0 = public 1 = private
	
	user addUser(in long uid, in string username, in string password);
	user login(in string username, in string password);
	user addFile(in string files);
	user changeFileStatus(in string files, in  short filestatus);
	user removeFile(in string files);
	};
	typedef sequence<user> users;
	
	interface listener{
		void message(in string message);
	};
	
	interface file{
	attribute string content;
	attribute string filename;
	attribute short fileid;
	attribute short filestatus;
	attribute long uid;

	
	
	
	 void register(in listener lt);
	file addFile(in string content, in string filename, in short fileid, in short filestatus);
	file changeFileStatus(in string filelist, in short fileid, in short filestatus);
	file fileUpdate(in string filelist, in long lastchanged, in  short fileid, in listener callback );
	file getFiles(in long uid, in string content, in string filename);
	file getFile(in long uid, in string filename, in string content);
	};
	typedef sequence<file> files;	
};