package filebox.userPackage;


/**
* filebox/userPackage/filesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public final class filesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public filesHolder ()
  {
  }

  public filesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.userPackage.filesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.userPackage.filesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.userPackage.filesHelper.type ();
  }

}
