package filebox;


/**
* filebox/filePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 26 March 2013 22:53:50 o'clock GMT
*/

public class filePOATie extends filePOA
{

  // Constructors

  public filePOATie ( filebox.fileOperations delegate ) {
      this._impl = delegate;
  }
  public filePOATie ( filebox.fileOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public filebox.fileOperations _delegate() {
      return this._impl;
  }
  public void _delegate (filebox.fileOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String content ()
  {
    return _impl.content();
  } // content
  public void content (String newContent)
  {
    _impl.content(newContent);
  } // content

  public String filename ()
  {
    return _impl.filename();
  } // filename
  public void filename (String newFilename)
  {
    _impl.filename(newFilename);
  } // filename

  public short fileid ()
  {
    return _impl.fileid();
  } // fileid
  public void fileid (short newFileid)
  {
    _impl.fileid(newFileid);
  } // fileid

  public short filestatus ()
  {
    return _impl.filestatus();
  } // filestatus
  public void filestatus (short newFilestatus)
  {
    _impl.filestatus(newFilestatus);
  } // filestatus

  public int uid ()
  {
    return _impl.uid();
  } // uid
  public void uid (int newUid)
  {
    _impl.uid(newUid);
  } // uid

  public void register (filebox.listener lt)
  {
    _impl.register(lt);
  } // register

  public filebox.file addFile (String content, String filename, short fileid, short filestatus)
  {
    return _impl.addFile(content, filename, fileid, filestatus);
  } // addFile

  public filebox.file changeFileStatus (String filelist, short fileid, short filestatus)
  {
    return _impl.changeFileStatus(filelist, fileid, filestatus);
  } // changeFileStatus

  public filebox.file fileUpdate (String filelist, int lastchanged, short fileid, filebox.listener callback)
  {
    return _impl.fileUpdate(filelist, lastchanged, fileid, callback);
  } // fileUpdate

  public filebox.file getFiles (int uid, String content, String filename)
  {
    return _impl.getFiles(uid, content, filename);
  } // getFiles

  public filebox.file getFile (int uid, String filename, String content)
  {
    return _impl.getFile(uid, filename, content);
  } // getFile

  private filebox.fileOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class filePOATie
