package filebox;


/**
* filebox/fileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 26 March 2013 22:53:50 o'clock GMT
*/

public interface fileOperations 
{
  String content ();
  void content (String newContent);
  String filename ();
  void filename (String newFilename);
  short fileid ();
  void fileid (short newFileid);
  short filestatus ();
  void filestatus (short newFilestatus);
  int uid ();
  void uid (int newUid);
  void register (filebox.listener lt);
  filebox.file addFile (String content, String filename, short fileid, short filestatus);
  filebox.file changeFileStatus (String filelist, short fileid, short filestatus);
  filebox.file fileUpdate (String filelist, int lastchanged, short fileid, filebox.listener callback);
  filebox.file getFiles (int uid, String content, String filename);
  filebox.file getFile (int uid, String filename, String content);
} // interface fileOperations
