package filebox;


/**
* filebox/filelistPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public class filelistPOATie extends filelistPOA
{

  // Constructors

  public filelistPOATie ( filebox.filelistOperations delegate ) {
      this._impl = delegate;
  }
  public filelistPOATie ( filebox.filelistOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public filebox.filelistOperations _delegate() {
      return this._impl;
  }
  public void _delegate (filebox.filelistOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String filename ()
  {
    return _impl.filename();
  } // filename
  public void filename (String newFilename)
  {
    _impl.filename(newFilename);
  } // filename

  public short fileid ()
  {
    return _impl.fileid();
  } // fileid
  public void fileid (short newFileid)
  {
    _impl.fileid(newFileid);
  } // fileid

  public short filestatus ()
  {
    return _impl.filestatus();
  } // filestatus
  public void filestatus (short newFilestatus)
  {
    _impl.filestatus(newFilestatus);
  } // filestatus

  public int lastchanged ()
  {
    return _impl.lastchanged();
  } // lastchanged
  public void lastchanged (int newLastchanged)
  {
    _impl.lastchanged(newLastchanged);
  } // lastchanged

  public String[] addFile (String filelist, String filename, short fileid, short filestatus)
  {
    return _impl.addFile(filelist, filename, fileid, filestatus);
  } // addFile

  public String[] changeFileStatus (String filelist, short fileid, short filestatus)
  {
    return _impl.changeFileStatus(filelist, fileid, filestatus);
  } // changeFileStatus

  public String[] fileUpdate (String filelist, int lastchanged, short fileid)
  {
    return _impl.fileUpdate(filelist, lastchanged, fileid);
  } // fileUpdate

  private filebox.filelistOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class filelistPOATie
