package filebox;


/**
* filebox/fileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 23 March 2013 12:02:46 o'clock GMT
*/

public interface fileOperations 
{
  String content ();
  void content (String newContent);
  String filename ();
  void filename (String newFilename);
  short fileid ();
  void fileid (short newFileid);
  short filestatus ();
  void filestatus (short newFilestatus);
  int lastchanged ();
  void lastchanged (int newLastchanged);
  int uid ();
  void uid (int newUid);
  filebox.file addFile (String filelist, String filename, short fileid, short filestatus);
  filebox.file changeFileStatus (String filelist, short fileid, short filestatus);
  filebox.file fileUpdate (String filelist, int lastchanged, short fileid);
  filebox.file getFiles (int uid);
  filebox.file getFile (int uid, String filename);
} // interface fileOperations
