package filebox;


/**
* filebox/filelistOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public interface filelistOperations 
{
  String filename ();
  void filename (String newFilename);
  short fileid ();
  void fileid (short newFileid);
  short filestatus ();
  void filestatus (short newFilestatus);
  int lastchanged ();
  void lastchanged (int newLastchanged);
  String[] addFile (String filelist, String filename, short fileid, short filestatus);
  String[] changeFileStatus (String filelist, short fileid, short filestatus);
  String[] fileUpdate (String filelist, int lastchanged, short fileid);
} // interface filelistOperations
