package filebox;


/**
* filebox/filelist.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public interface filelist extends filelistOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface filelist
