package filebox;


/**
* filebox/userPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public class userPOATie extends userPOA
{

  // Constructors

  public userPOATie ( filebox.userOperations delegate ) {
      this._impl = delegate;
  }
  public userPOATie ( filebox.userOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public filebox.userOperations _delegate() {
      return this._impl;
  }
  public void _delegate (filebox.userOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int uid ()
  {
    return _impl.uid();
  } // uid

  public String name ()
  {
    return _impl.name();
  } // name
  public void name (String newName)
  {
    _impl.name(newName);
  } // name

  public String password ()
  {
    return _impl.password();
  } // password
  public void password (String newPassword)
  {
    _impl.password(newPassword);
  } // password

  public int lastlogin ()
  {
    return _impl.lastlogin();
  } // lastlogin
  public void lastlogin (int newLastlogin)
  {
    _impl.lastlogin(newLastlogin);
  } // lastlogin

  public short filestatus ()
  {
    return _impl.filestatus();
  } // filestatus
  public void filestatus (short newFilestatus)
  {
    _impl.filestatus(newFilestatus);
  } // filestatus

  public filebox.user addUser (int uid, String name, String password)
  {
    return _impl.addUser(uid, name, password);
  } // addUser

  public filebox.user addFile (String files)
  {
    return _impl.addFile(files);
  } // addFile

  public filebox.user changeFileStatus (String files, short filestatus)
  {
    return _impl.changeFileStatus(files, filestatus);
  } // changeFileStatus

  public filebox.user removeFile (String files)
  {
    return _impl.removeFile(files);
  } // removeFile

  public filebox.user checkFileUpdates (String files, int lastlogin, String filename)
  {
    return _impl.checkFileUpdates(files, lastlogin, filename);
  } // checkFileUpdates

  private filebox.userOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class userPOATie
