package filebox;


/**
* filebox/user.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 26 March 2013 19:45:27 o'clock GMT
*/

public interface user extends userOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface user
