package filebox;


/**
* filebox/userOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public interface userOperations 
{
  int uid ();
  String name ();
  void name (String newName);
  String password ();
  void password (String newPassword);
  int lastlogin ();
  void lastlogin (int newLastlogin);
  short filestatus ();
  void filestatus (short newFilestatus);
  filebox.user addUser (int uid, String name, String password);
  filebox.user addFile (String files);
  filebox.user changeFileStatus (String files, short filestatus);
  filebox.user removeFile (String files);
  filebox.user checkFileUpdates (String files, int lastlogin, String filename);
} // interface userOperations
