package filebox;


/**
* filebox/filesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 10:15:42 AM BST
*/

public final class filesHolder implements org.omg.CORBA.portable.Streamable
{
  public filebox.file value[] = null;

  public filesHolder ()
  {
  }

  public filesHolder (filebox.file[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.filesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.filesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.filesHelper.type ();
  }

}
