package filebox;


/**
* filebox/file.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Tuesday, April 2, 2013 10:15:42 AM BST
*/

public interface file extends fileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface file
