package filebox;


/**
* filebox/MessageServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Saturday, April 6, 2013 6:25:21 PM BST
*/

public interface MessageServerOperations 
{
  void register (filebox.listener lt);
} // interface MessageServerOperations
