package filebox;


/**
* filebox/statusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Saturday, April 6, 2013 6:25:21 PM BST
*/

public interface statusOperations 
{
  int code ();
  void code (int newCode);

  // 0 - success, 1 - error
  String text ();

  // 0 - success, 1 - error
  void text (String newText);
} // interface statusOperations
