package filebox;


/**
* filebox/user.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../filebox.idl
* Saturday, April 6, 2013 6:25:21 PM BST
*/

public interface user extends userOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface user
