package filebox.filelistPackage;


/**
* filebox/filelistPackage/filelistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from filebox.idl
* 22 March 2013 23:23:23 o'clock GMT
*/

public final class filelistHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public filelistHolder ()
  {
  }

  public filelistHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = filebox.filelistPackage.filelistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    filebox.filelistPackage.filelistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return filebox.filelistPackage.filelistHelper.type ();
  }

}
